### ISSUE TITLE
Estudo do Método Git-Flow

### ISSUE THREAD

**Issue by CayoNikolas** [LucasBarbosaSilva/FazendinhaBarbosa#5]
Estudar e implementar o método de fluxo de trabalho Git-Flow para empregá-lo no projeto.

**Comment by CayoNikolas** [comment]
Usando o link a seguir como base para implementação do GitFlow. Realizando testes antes de aplicá-lo no projeto.

https://www.atlassian.com/br/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by LucasBarbosaSilva** [comment]
Definições do projeto:
**Branchs:**
- Haverá duas branchs principais: main e a dev. 
- Para cada task deve ser criada uma banch auxiliar para as respectivas alterações.
- Terminou a taks, dá um merge na dev.
- O nome da branch deve ser o nome da taks separado por ífens.
- Quando houver uma versão pronta para produção, será criado uma branch de release da branch de dev e desta será feito um merge para a branch main.
- Quando houver a descoberta de um bug será criado uma branch com o nome do bug relatado.

**Commits:**
- Os commits devem seguir a estrutura do commit semântico: <tipo>[escopo opcional]: <descrição> (https://blog.geekhunter.com.br/o-que-e-commit-e-como-usar-commits-semanticos)
- A descrição deve ser inglês e dar conta de explicar o que a alteração fez.
- Commits devem alterações pontuais. Várias alterações devem ser separadas em commits diferentes.
